### ISSUE TITLE
Scss compiler error: Error: Error: done is not a function

### ISSUE THREAD

**Issue by pograjak** [Hernanm0g/meteor-vuetify-loader#1]
Hey! I really like the idea behind this project. 

But when I try it, I get `Scss compiler error: Error: Error: done is not a function` error. In a cli i can see it gets right scss file. 

It seems it has a problem with a `@import anotherfile;` // in a relative path 

Have you experienced something like that? 

Keep going. :]

**Comment by Hernanm0g** [comment]
Hi @pograjak . Ill be attending this issue today.

**Comment by Hernanm0g** [comment]
Hi @pograjak . Plese provide the error stack trace and the scss file that is causing problems so i can reproduce the error locally.

**Comment by pograjak** [comment]
Hey, I've found out that the problem is again with the paths, and the error was crashing on a @import line.
