### ISSUE TITLE
Problem with importing Vuetify components

### ISSUE THREAD

**Issue by pograjak** [Hernanm0g/meteor-vuetify-loader#2]
Hey, 

trying to make it work. Right now I've got problem with dependecies:
Seems to be problem with:

https://github.com/Hernanm0g/meteor-vuetify-loader/blob/3883149025a4bf03e5a99b4b34f16ffc7da8e19a/plugins/utils/vuetifySfcProcesser.js#L78

I have components defined in a meteor package for example pckgA  imported into another package (pckgB) and then built. But it seems like it is searching for vuetify components inside `pckgA/node_modules/vuetify/lib/components/....` but inside pckgA there is no node_module. It is only inside pckgB.

**Comment by Hernanm0g** [comment]
Ok. I may have an idea of how to solve this. Lets see...

**Comment by Hernanm0g** [comment]
Hi @pograjak . Can you provide an example so i can reproduce this locally?

**Comment by pograjak** [comment]
@Hernanm0g Hi! I am not sure how to provice an example cuz, it is a private repo, where I am trying to run it. But lets see. In the project we have structure to write every code into a [meteor packages](https://guide.meteor.com/writing-atmosphere-packages.html) and not just into the source dir. Is there anything else that would help you?

**Comment by Hernanm0g** [comment]
Ok @pograjak . I get it. Please contact me in private: hernanmog@gmail.com.
