### ISSUE TITLE
On-the-fly not working?

### ISSUE THREAD

**Issue by MarkPWebb** [Hernanm0g/meteor-vuetify-loader#6]
I've installed the Hernanm0g:meteor_vuetify and tried to use the meteor-vuetfiy-loader to have Vuetify components loaded on the fly. I've followed all the steps but when I look at the app in the visualiser the entire Vuetify library has been included (1.09MB).

Have I missed something? Or is there any information I can provide to help work out what's going on. This project is a great idea and sorely needed. I'd love to see it work.

**Comment by Hernanm0g** [comment]
Hi @MarkPWebb.

Thanks for the feedback. This feature is currently being developed, and no success yet, but we're close to get it working. The importance here is that import Vuetify from 'vuetify/lib' (In client), is loading all Vuetify components and sass files into the client bundle at once, so we might need to replace that with a lighter import solution. 

Please be patient, and staty tuned, soon you'll see the "on the fly" working.

**Comment by MarkPWebb** [comment]
That's great to hear. I mistakenly assumed it was fully functional but applaud your efforts to pull this off. It will be a huge benefit. 

As far as actually getting Vuetify working with the full lib, it works perfectly.

**Comment by Hernanm0g** [comment]
Hi @MarkPWebb . Finally we achieved to reduce the vuetify's bundle size to 500Kb. Just follow thid instructions:
```javascript
import Vue from 'vue'
import '@mdi/font/css/materialdesignicons.min.css' // Ensure you are using css-loader, Note the .min.css
// Import custom variables 
import minifyTheme from 'minify-css-string' // Lib to minify theme

/*--------  The magic goes here  --------*/
import Vuetify from 'vuetify/lib/framework' // This will load only the basic framework. Will ignore components
import 'vuetify/lib/util/colors' // This will Load colors presets
import 'vuetify/lib/directives' // This will load directives

Vue.use(Vuetify)

// Language
// Translation provided by Vuetify (javascript)
// import es from 'vuetify/es5/locale/es'


const opts = {
  theme: {
    options: { minifyTheme },
  },
  icons: {
    iconfont: 'mdi', // default - only for display purposes
  },
}
export default new Vuetify(opts)
```

**Comment by Hernanm0g** [comment]
Before:
![Captura de pantalla de 2021-02-26 19-56-29](https://user-images.githubusercontent.com/36971322/109370487-8818e280-786e-11eb-943a-8b0e485d0049.png)

After:
![Captura de pantalla de 2021-02-26 19-53-17](https://user-images.githubusercontent.com/36971322/109370493-91a24a80-786e-11eb-837f-65ae9a27c0e8.png)

**Comment by Hernanm0g** [comment]
One more thing.
Please note that using:
```javascript
import Vuetify from 'vuetify/lib/framework'
import 'vuetify/lib/util/colors'
import 'vuetify/lib/directives'
```
**will break HMR** , so while developing, keep using: 
  ```javascript
import Vuetify from 'vuetify/lib'
```
And in production use the lighter solution based on /lib/framework.

**Comment by MarkPWebb** [comment]
Thank you. Works great. Can't wait to see if you can get further improvements.

**Comment by Hernanm0g** [comment]
Hey @MarkPWebb . Check out the Meteor-Vuetify's Performance at lighthouse. https://github.com/Hernanm0g/meteor_vuetify#check-out-the-meteor-vuetifys-performance
