### ISSUE TITLE
Scss compiler error: Error: $map: null is not a map.\n

### ISSUE THREAD

**Issue by ackzell** [Hernanm0g/meteor-vuetify-loader#9]
Hey @Hernanm0g, 

Just to report I could not find a way to update a variable from Vuetify, namely change the background color for my app using the reference to `$material-light` or `$material-dark`:

```scss
$material-light: (
  "background": "#FF0000", 
);
```

Attaching an image where you can see I updated the `user_variables.scss` file in the [awesome boilerplate you created with this loader prepared](https://github.com/Hernanm0g/meteor_vuetify) , and some variables like the `$btn-sizes` can be overriden no problem. But this `$material-light` one throws an error:

```bash

/home/ackzell/.meteor/packages/coffeescript/.1.0.17.1eorg4y.umwx++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
{
  message: 'Scss compiler error: Error: $map: null is not a map.\n' +
    '   ╷\n' +
    '41 │     $map: map-get($map, $key)\n' +
    '   │           ^^^^^^^^^^^^^^^^^^^\n' +
    '   ╵\n' +
    '  node_modules/vuetify/src/styles/tools/_functions.sass 41:11  map-deep-get()\n' +
    '  node_modules/vuetify/src/components/VApp/VApp.sass 8:10      @content\n' +
    '  node_modules/vuetify/src/styles/tools/_theme.sass 3:5        theme()\n' +
    '  node_modules/vuetify/src/components/VApp/VApp.sass 6:1       root stylesheet,\n',
  info: {
    file: '/node_modules/vuetify/src/components/VApp/VApp.sass',
    line: undefined,
    column: undefined,
    func: undefined
  }
}

```

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/601266/118536590-85ad8280-b711-11eb-9fb2-c9bf8acac49c.png)

</details>

**Comment by Ovsdrak** [comment]
I'm having this issue too. The only one reason I needed to install this package is for overriding the $material-dark and $material-light SASS map variables. Hope to be fixed soon!

**Comment by Hernanm0g** [comment]
Sorry @ackzell  and @Ovsdrak, ive been pretty busy last months. I will try to look at this on weeken, lets see.

**Comment by Hernanm0g** [comment]
@ackzell @Ovsdrak . This bug has been fixed in the latest version of the package.
Please make sure that HEX colors are not inside quotes:
```sass
$btn-sizes: (
  'default': 60,
  'large': 90
);
$material-light: (
  'background': #F06292, 
);
```

**Comment by Ovsdrak** [comment]
Thanks @Hernanm0g!

**Comment by Ovsdrak** [comment]
@Hernanm0g I tried to use the latest version, but it throws the following error:

```
➜  spa-cover-admin git:(spa-cover-form-ui) ✗ meteor add zer0th:meteor-vuetify-loader@0.1.41                                                               
 => Errors while adding packages:             
                                              
While selecting package versions:
error: No version of zer0th:meteor-vuetify-loader satisfies all constraints: @0.1.41, @=0.1.40
Constraints on package "zer0th:meteor-vuetify-loader":
* zer0th:meteor-vuetify-loader@0.1.41 <- top level
* zer0th:meteor-vuetify-loader@=0.1.40 <- top level
```

Do you have some idea of how to solve this issue?

**Comment by Hernanm0g** [comment]
Hi @Ovsdrak.
Please try removing the version constraint:
`meteor add zer0th:meteor-vuetify-loader`
Or simply
`meteor update zer0th:meteor-vuetify-loader`
